default moralfinalbom = 0
default mostraranel = 0
default pegaranel = 0
define procuramesapai = 0
define procuraescrivaninhapai = 0
define procuragavetaspai = 0
define vivianescolha = 0
# para adicionar moral use $ moral += 1
# para remover moral Use $ moral -= 1
